server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
  application:
    name: service-order
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        name: order
    sentinel:
      transport:
        port: 9962 #和sentinel 控制交互的端口号，随意指定
        dashboard: 127.0.0.1:9926 # sentinel控制台服务的地址
      # 从1.6.3版本开始，sentinel web filter 默认收敛所有URL的入口context，导致链路限流不生效
      filter:
        # Enable to instance CommonFilter 关闭CommonFilter实例化 。添加配置类，构建CommonFilter实例
        enabled: false
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.78.168:3306/test-sql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: hsmxg
    password: hsmxg1204.
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 # rocketmq:
  #  name-server: 192.168.109.131:9876
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    max-history: 7
    max-size: 2MB
    name: E:/SpringBootLearing/test_logs/login.log

  level:
    cn.hsmxg1204.test: info

service-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule